import { useState } from "react";
import { motion } from "motion/react";
import { FileText, Upload, Download, Sparkles, AlertTriangle, CheckCircle, Loader2, File, X, Eye, EyeOff } from "lucide-react";
import { GoogleGenerativeAI } from "@google/generative-ai";
import { useTranslation } from "react-i18next";

export default function ReportAnalysis() {
  const { t } = useTranslation();
  const [file, setFile] = useState(null);
  const [isAnalyzing, setIsAnalyzing] = useState(false);
  const [analysis, setAnalysis] = useState(null);

  const handleFileUpload = (e) => {
    const uploadedFile = e.target.files[0];
    if (!uploadedFile) return;
    
    const ext = uploadedFile.name.split('.').pop().toLowerCase();
    const isSupported = uploadedFile.type === 'application/pdf' || 
                        uploadedFile.type.startsWith('image/') ||
                        ['pdf', 'png', 'jpg', 'jpeg'].includes(ext);
                        
    if (isSupported) {
      setFile(uploadedFile);
      setAnalysis(null);
    } else {
      alert(t('reportAnalysis.uploadError', 'Unsupported file format. Please upload a PDF, PNG, JPG, or JPEG file.'));
    }
  };

  const analyzeReport = async () => {
    if (!file) return;

    setIsAnalyzing(true);
    try {
      const formData = new FormData();
      formData.append("file", file);
      const token = localStorage.getItem("medico_token");
      const API_BASE = import.meta.env.VITE_API_BASE_URL || "https://medassistai-5.onrender.com";

      const response = await fetch(`${API_BASE}/gemini/analyze_report`, {
        method: "POST",
        headers: {
          "Authorization": `Bearer ${token}`
        },
        body: formData
      });

      if (!response.ok) {
        const errorData = await response.json().catch(() => ({ message: "Analysis failed" }));
        throw new Error(errorData.message || "Analysis failed");
      }

      const data = await response.json();
      
      if (data.success) {
        setAnalysis(data);
      } else {
        throw new Error(data.message || t('reportAnalysis.analysisError', 'Failed to analyze report'));
      }
    } catch (error) {
      console.error('Error analyzing report:', error);
      alert(error.message || t('reportAnalysis.analysisError', 'Error analyzing report. Please try again.'));
    } finally {
      setIsAnalyzing(false);
    }
  };

  const readFileContent = (file) => {
    return new Promise((resolve, reject) => {
      const reader = new FileReader();
      reader.onload = (e) => resolve(e.target.result);
      reader.onerror = reject;
      reader.readAsText(file);
    });
  };

  const downloadSummary = () => {
    if (!analysis) return;

    const summaryText = `
MEDICAL REPORT SUMMARY - MedAssist AI
=====================================

SUMMARY:
${analysis.summary}

MEDICAL TERMS EXPLAINED:
${analysis.medicalTerms.map(t => `- ${t.term}: ${t.explanation}`).join('\n')}

ABNORMAL VALUES:
${analysis.abnormalValues.map(v => `- ${v.test}: ${v.value} (Normal: ${v.normal}) - ${v.status}`).join('\n')}

HEALTH RECOMMENDATIONS:
${analysis.recommendations.map(r => `- ${r}`).join('\n')}

OVERALL HEALTH ASSESSMENT:
${analysis.healthAssessment}

Generated by MedAssist AI - AI-Powered Healthcare Assistant
    `;

    const blob = new Blob([summaryText], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = t('reportAnalysis.downloadSummary', 'medical-report-summary.txt');
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="min-h-screen bg-gray-50 p-6">
      <div className="max-w-6xl mx-auto">
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          className="mb-8"
        >
          <h1 className="text-3xl font-bold text-gray-900 mb-2">{t('reportAnalysis.title', 'Medical Report Analysis')}</h1>
          <p className="text-gray-600">{t('reportAnalysis.description', 'AI-powered medical report summarization')}</p>
        </motion.div>

        <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
          {/* Upload Section */}
          <motion.div
            initial={{ opacity: 0, x: -20 }}
            animate={{ opacity: 1, x: 0 }}
            className="bg-white rounded-2xl shadow-sm p-6"
          >
            <h2 className="text-xl font-bold text-gray-900 mb-4 flex items-center gap-2">
              <Upload className="w-5 h-5 text-emerald-600" />
              {t('reportAnalysis.upload', 'Upload Medical Report')}
            </h2>

            <div className="border-2 border-dashed border-gray-300 rounded-xl p-8 text-center hover:border-emerald-500 transition-colors">
              <input
                type="file"
                accept=".pdf,.png,.jpg,.jpeg"
                onChange={handleFileUpload}
                className="hidden"
                id="file-upload"
              />
              <label
                htmlFor="file-upload"
                className="cursor-pointer"
              >
                <FileText className="w-16 h-16 mx-auto mb-4 text-gray-400" />
                <p className="text-gray-600 mb-2">{t('reportAnalysis.uploadPlaceholder', 'Click to upload or drag and drop')}</p>
                <p className="text-sm text-gray-400">{t('reportAnalysis.fileTypes', 'PDF, PNG, JPG, or JPEG only')}</p>
              </label>
            </div>

            {file && (
              <motion.div
                initial={{ opacity: 0, y: 10 }}
                animate={{ opacity: 1, y: 0 }}
                className="mt-4 p-4 bg-emerald-50 rounded-xl border border-emerald-200 flex items-center justify-between"
              >
                <div className="flex items-center gap-3">
                  <File className="w-8 h-8 text-emerald-600" />
                  <div>
                    <p className="font-semibold text-gray-900">{file.name}</p>
                    <p className="text-sm text-gray-600">{(file.size / 1024).toFixed(2)} KB</p>
                  </div>
                </div>
                <button
                  onClick={() => setFile(null)}
                  className="p-2 hover:bg-emerald-100 rounded-lg transition-colors"
                >
                  <X className="w-5 h-5 text-gray-600" />
                </button>
              </motion.div>
            )}

            <button
              onClick={analyzeReport}
              disabled={!file || isAnalyzing}
              className="w-full mt-4 bg-gradient-to-r from-emerald-600 to-emerald-700 text-white py-3 rounded-xl font-semibold hover:from-emerald-700 hover:to-emerald-800 transition-all disabled:opacity-50 disabled:cursor-not-allowed flex items-center justify-center gap-2"
            >
              {isAnalyzing ? (
                <>
                  <Loader2 className="w-5 h-5 animate-spin" />
                  {t('reportAnalysis.analyzing', 'Analyzing with AI...')}
                </>
              ) : (
                <>
                  <Sparkles className="w-5 h-5" />
                  {t('reportAnalysis.analyze', 'Analyze Report')}
                </>
              )}
            </button>
          </motion.div>

          {/* Analysis Results */}
          <motion.div
            initial={{ opacity: 0, x: 20 }}
            animate={{ opacity: 1, x: 0 }}
            className="bg-white rounded-2xl shadow-sm p-6"
          >
            <h2 className="text-xl font-bold text-gray-900 mb-4 flex items-center gap-2">
              <FileText className="w-5 h-5 text-emerald-600" />
              {t('reportAnalysis.results', 'Analysis Results')}
            </h2>

            {!analysis ? (
              <div className="text-center py-12 text-gray-500">
                <Sparkles className="w-16 h-16 mx-auto mb-4 text-gray-300" />
                <p className="text-lg font-medium mb-2">{t('reportAnalysis.noResults', 'AI-Powered Report Analysis')}</p>
                <p className="text-sm">{t('reportAnalysis.uploadPrompt', 'Upload a medical report to get AI-generated summary and insights')}</p>
              </div>
            ) : (
              <div className="space-y-4 max-h-[600px] overflow-y-auto">
                {/* Summary */}
                <motion.div
                  initial={{ opacity: 0, y: 10 }}
                  animate={{ opacity: 1, y: 0 }}
                  className="p-4 bg-blue-50 rounded-xl border border-blue-200"
                >
                  <h3 className="font-semibold text-gray-900 mb-2">{t('reportAnalysis.summary', 'Report Summary')}</h3>
                  <p className="text-sm text-gray-700 leading-relaxed">{analysis.summary}</p>
                </motion.div>

                {/* Medical Terms */}
                <motion.div
                  initial={{ opacity: 0, y: 10 }}
                  animate={{ opacity: 1, y: 0 }}
                  transition={{ delay: 0.1 }}
                  className="p-4 bg-purple-50 rounded-xl border border-purple-200"
                >
                  <h3 className="font-semibold text-gray-900 mb-3">{t('reportAnalysis.terms', 'Medical Terms Explained')}</h3>
                  <div className="space-y-2">
                    {analysis.medicalTerms.map((term, index) => (
                      <div key={index} className="bg-white p-3 rounded-lg border border-purple-200">
                        <p className="font-semibold text-gray-900">{term.term}</p>
                        <p className="text-sm text-gray-700">{term.explanation}</p>
                      </div>
                    ))}
                  </div>
                </motion.div>

                {/* Abnormal Values */}
                {analysis.abnormalValues && analysis.abnormalValues.length > 0 && (
                  <motion.div
                    initial={{ opacity: 0, y: 10 }}
                    animate={{ opacity: 1, y: 0 }}
                    transition={{ delay: 0.2 }}
                    className="p-4 bg-red-50 rounded-xl border border-red-200"
                  >
                    <h3 className="font-semibold text-gray-900 mb-3 flex items-center gap-2">
                      <AlertTriangle className="w-5 h-5 text-red-500" />
                      {t('reportAnalysis.abnormalValues', 'Abnormal Values Detected')}
                    </h3>
                    <div className="space-y-3">
                      {analysis.abnormalValues.map((item, index) => (
                        <div key={index} className="bg-white p-3 rounded-lg border border-red-100 flex justify-between items-center">
                          <div>
                            <p className="font-semibold text-gray-900">{item.test}</p>
                            <p className="text-xs text-gray-500">Normal Range: {item.normal}</p>
                          </div>
                          <div className="text-right">
                            <p className="font-bold text-red-600">{item.value}</p>
                            <p className="text-xs text-red-500">{item.status}</p>
                          </div>
                        </div>
                      ))}
                    </div>
                  </motion.div>
                )}

                {/* Recommendations */}
                <motion.div
                  initial={{ opacity: 0, y: 10 }}
                  animate={{ opacity: 1, y: 0 }}
                  transition={{ delay: 0.3 }}
                  className="p-4 bg-emerald-50 rounded-xl border border-emerald-200"
                >
                  <h3 className="font-semibold text-gray-900 mb-3 flex items-center gap-2">
                    <CheckCircle className="w-5 h-5 text-emerald-500" />
                    {t('reportAnalysis.recommendations', 'Health Recommendations')}
                  </h3>
                  <ul className="space-y-2">
                    {analysis.recommendations.map((rec, index) => (
                      <li key={index} className="flex gap-2 text-sm text-gray-700 bg-white p-3 rounded-lg border border-emerald-100">
                        <div className="w-1.5 h-1.5 rounded-full bg-emerald-500 mt-1.5 flex-shrink-0" />
                        <span>{rec}</span>
                      </li>
                    ))}
                  </ul>
                </motion.div>

                {/* Overall Assessment */}
                <motion.div
                  initial={{ opacity: 0, y: 10 }}
                  animate={{ opacity: 1, y: 0 }}
                  transition={{ delay: 0.4 }}
                  className="p-4 bg-orange-50 rounded-xl border border-orange-200"
                >
                  <h3 className="font-semibold text-gray-900 mb-2">{t('reportAnalysis.overallAssessment', 'Overall Assessment')}</h3>
                  <p className="text-sm text-gray-700 leading-relaxed">{analysis.healthAssessment}</p>
                </motion.div>

                <button
                  onClick={downloadSummary}
                  className="w-full mt-4 bg-white text-emerald-600 border border-emerald-200 py-3 rounded-xl font-semibold hover:bg-emerald-50 transition-colors flex items-center justify-center gap-2 shadow-sm"
                >
                  <Download className="w-5 h-5" />
                  {t('reportAnalysis.downloadBtn', 'Download Summary (TXT)')}
                </button>
              </div>
            )}
          </motion.div>
        </div>
      </div>
    </div>
  );
}
