export const reports = [
  {
    id: "LR-10241",
    patientName: "Aarav Sharma",
    patientId: "P-2041",
    patientAge: 34,
    patientGender: "Male",
    testName: "Complete Blood Count",
    testType: "Hematology",
    doctor: "Dr. Meera Iyer",
    doctorSpecialty: "General Physician",
    sampleDate: "2026-05-14",
    reportDate: "2026-05-15",
    status: "Completed",
    notes: "All values within normal range.",
    history: [
      { date: "2026-05-14 09:12", event: "Sample collected" },
      { date: "2026-05-14 11:30", event: "Sample received in lab" },
      { date: "2026-05-15 08:45", event: "Analysis completed" },
      { date: "2026-05-15 10:20", event: "Report verified & released" },
    ],
    attachments: [],
  },
  {
    id: "LR-10242",
    patientName: "Priya Nair",
    patientId: "P-2042",
    patientAge: 28,
    patientGender: "Female",
    testName: "Lipid Profile",
    testType: "Biochemistry",
    doctor: "Dr. Rohan Mehta",
    doctorSpecialty: "Cardiologist",
    sampleDate: "2026-05-15",
    reportDate: "â€”",
    status: "Pending",
    history: [{ date: "2026-05-15 08:00", event: "Sample collected" }],
    attachments: [],
  },
  {
    id: "LR-10243",
    patientName: "Vikram Singh",
    patientId: "P-2043",
    patientAge: 45,
    patientGender: "Male",
    testName: "Thyroid Function (TSH, T3, T4)",
    testType: "Endocrinology",
    doctor: "Dr. Anjali Rao",
    doctorSpecialty: "Endocrinologist",
    sampleDate: "2026-05-15",
    reportDate: "â€”",
    status: "In Progress",
    history: [
      { date: "2026-05-15 07:40", event: "Sample collected" },
      { date: "2026-05-15 09:10", event: "Analysis in progress" },
    ],
    attachments: [],
  },
  {
    id: "LR-10244",
    patientName: "Sneha Kapoor",
    patientId: "P-2044",
    patientAge: 31,
    patientGender: "Female",
    testName: "HbA1c",
    testType: "Biochemistry",
    doctor: "Dr. Karan Verma",
    doctorSpecialty: "Diabetologist",
    sampleDate: "2026-05-13",
    reportDate: "2026-05-14",
    status: "Completed",
    notes: "Within target range.",
    history: [
      { date: "2026-05-13 10:00", event: "Sample collected" },
      { date: "2026-05-14 09:30", event: "Report released" },
    ],
    attachments: [],
  },
  {
    id: "LR-10245",
    patientName: "Rahul Desai",
    patientId: "P-2045",
    patientAge: 52,
    patientGender: "Male",
    testName: "Liver Function Test",
    testType: "Biochemistry",
    doctor: "Dr. Meera Iyer",
    doctorSpecialty: "General Physician",
    sampleDate: "2026-05-12",
    reportDate: "â€”",
    status: "Cancelled",
    notes: "Patient requested cancellation",
    history: [
      { date: "2026-05-12 08:00", event: "Sample collected" },
      { date: "2026-05-12 12:30", event: "Cancelled by patient" },
    ],
    attachments: [],
  },
  {
    id: "LR-10246",
    patientName: "Ananya Joshi",
    patientId: "P-2046",
    patientAge: 24,
    patientGender: "Female",
    testName: "Urine Routine",
    testType: "Pathology",
    doctor: "Dr. Anjali Rao",
    doctorSpecialty: "Nephrologist",
    sampleDate: "2026-05-16",
    reportDate: "â€”",
    status: "Pending",
    history: [{ date: "2026-05-16 07:30", event: "Sample collected" }],
    attachments: [],
  },
  {
    id: "LR-10247",
    patientName: "Mohit Bansal",
    patientId: "P-2047",
    patientAge: 39,
    patientGender: "Male",
    testName: "Vitamin D",
    testType: "Biochemistry",
    doctor: "Dr. Rohan Mehta",
    doctorSpecialty: "Cardiologist",
    sampleDate: "2026-05-16",
    reportDate: "â€”",
    status: "In Progress",
    notes: "High-priority analysis",
    history: [
      { date: "2026-05-16 08:10", event: "Sample collected" },
      { date: "2026-05-16 10:00", event: "Analysis in progress" },
    ],
    attachments: [],
  },
  {
    id: "LR-10248",
    patientName: "Ishita Reddy",
    patientId: "P-2048",
    patientAge: 29,
    patientGender: "Female",
    testName: "CRP (C-Reactive Protein)",
    testType: "Immunology",
    doctor: "Dr. Karan Verma",
    doctorSpecialty: "Internal Medicine",
    sampleDate: "2026-05-11",
    reportDate: "2026-05-12",
    status: "Completed",
    notes: "Results indicate inflammation.",
    history: [
      { date: "2026-05-11 09:00", event: "Sample collected" },
      { date: "2026-05-12 09:00", event: "Report released" },
    ],
    attachments: [],
  },
  {
    id: "LR-10249",
    patientName: "Deepak Kumar",
    patientId: "P-2049",
    patientAge: 41,
    patientGender: "Male",
    testName: "Kidney Function Test",
    testType: "Biochemistry",
    doctor: "Dr. Meera Iyer",
    doctorSpecialty: "General Physician",
    sampleDate: "2026-05-10",
    reportDate: "2026-05-11",
    status: "Completed",
    notes: "All parameters normal.",
    history: [
      { date: "2026-05-10 09:15", event: "Sample collected" },
      { date: "2026-05-11 08:00", event: "Report released" },
    ],
    attachments: [],
  },
  {
    id: "LR-10250",
    patientName: "Neha Singh",
    patientId: "P-2050",
    patientAge: 26,
    patientGender: "Female",
    testName: "Blood Sugar (Fasting)",
    testType: "Biochemistry",
    doctor: "Dr. Karan Verma",
    doctorSpecialty: "Diabetologist",
    sampleDate: "2026-05-16",
    reportDate: "â€”",
    status: "In Progress",
    history: [
      { date: "2026-05-16 06:30", event: "Sample collected" },
      { date: "2026-05-16 08:45", event: "Analysis in progress" },
    ],
    attachments: [],
  },
];
