export const tests = [
  {
    id: "T-001",
    code: "CBC",
    name: "Complete Blood Count",
    category: "Hematology",
    sampleType: "Whole Blood (EDTA)",
    price: 350,
    tat: "4 hrs",
    method: "Automated Cell Counter",
    description: "Measures RBC, WBC, platelets and hemoglobin levels to diagnose blood disorders.",
    status: "Active",
  },
  {
    id: "T-002",
    code: "LIPID",
    name: "Lipid Profile",
    category: "Biochemistry",
    sampleType: "Serum",
    price: 600,
    tat: "8 hrs",
    method: "Enzymatic Colorimetric",
    description: "Total cholesterol, HDL, LDL, triglycerides for cardiovascular risk assessment.",
    status: "Active",
  },
  {
    id: "T-003",
    code: "TSH",
    name: "Thyroid Function (TSH, T3, T4)",
    category: "Endocrinology",
    sampleType: "Serum",
    price: 750,
    tat: "12 hrs",
    method: "CLIA",
    description: "Thyroid hormone profile to assess thyroid function.",
    status: "Active",
  },
  {
    id: "T-004",
    code: "HBA1C",
    name: "HbA1c",
    category: "Biochemistry",
    sampleType: "Whole Blood",
    price: 450,
    tat: "6 hrs",
    method: "HPLC",
    description: "Average blood glucose levels over 3 months for diabetes monitoring.",
    status: "Active",
  },
  {
    id: "T-005",
    code: "LFT",
    name: "Liver Function Test",
    category: "Biochemistry",
    sampleType: "Serum",
    price: 700,
    tat: "8 hrs",
    method: "Spectrophotometry",
    description: "Liver enzymes and proteins panel to assess liver health.",
    status: "Active",
  },
  {
    id: "T-006",
    code: "URINE",
    name: "Urine Routine",
    category: "Pathology",
    sampleType: "Urine",
    price: 200,
    tat: "3 hrs",
    method: "Microscopy + Dipstick",
    description: "Physical, chemical, and microscopic urine analysis.",
    status: "Active",
  },
  {
    id: "T-007",
    code: "VITD",
    name: "Vitamin D (25-OH)",
    category: "Biochemistry",
    sampleType: "Serum",
    price: 1200,
    tat: "24 hrs",
    method: "CLIA",
    description: "Vitamin D deficiency screening and assessment.",
    status: "Active",
  },
  {
    id: "T-008",
    code: "CRP",
    name: "CRP (C-Reactive Protein)",
    category: "Immunology",
    sampleType: "Serum",
    price: 550,
    tat: "8 hrs",
    method: "Latex Agglutination",
    description: "Marker for inflammation and infection.",
    status: "Active",
  },
  {
    id: "T-009",
    code: "KFT",
    name: "Kidney Function Test",
    category: "Biochemistry",
    sampleType: "Serum",
    price: 500,
    tat: "6 hrs",
    method: "Colorimetric",
    description: "Creatinine, BUN, and other kidney function parameters.",
    status: "Active",
  },
  {
    id: "T-010",
    code: "BLOOD_SUGAR",
    name: "Blood Sugar (Fasting & Random)",
    category: "Biochemistry",
    sampleType: "Serum",
    price: 150,
    tat: "2 hrs",
    method: "Enzymatic",
    description: "Blood glucose measurement for diabetes screening.",
    status: "Active",
  },
  {
    id: "T-011",
    code: "THYROID_AUTO",
    name: "Thyroid Antibodies",
    category: "Immunology",
    sampleType: "Serum",
    price: 900,
    tat: "24 hrs",
    method: "CLIA",
    description: "TPO and Thyroglobulin antibodies for autoimmune thyroid disease.",
    status: "Inactive",
  },
  {
    id: "T-012",
    code: "GLUCOSE_CURVE",
    name: "Glucose Tolerance Test (GTT)",
    category: "Biochemistry",
    sampleType: "Serum (Multiple)",
    price: 800,
    tat: "3 hrs",
    method: "Enzymatic",
    description: "Oral glucose tolerance test for diabetes diagnosis.",
    status: "Active",
  },
];
